global:
  scrape_interval:     30s
  scrape_timeout:      15s
scrape_configs:
  - job_name: telegraf
    metrics_path: /metrics
    static_configs:
      - targets: ["telegraf:9273"]
  - job_name: MetricsML
    scrape_interval:     60s
    scrape_timeout:      30s
    metrics_path: /metrics
    static_configs:
      - targets: ["metricsml:8000"]
