apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: 'mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04'
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        - name: MSSQL_AGENT_ENABLED
          value: 'true'
        - name: MSSQL_DATA_DIR
          value: '/data'
        - name: MSSQL_LOG_DIR
          value: '/log'
        volumeMounts:
        - name: system
          mountPath: /var/opt/mssql
        - name: data
          mountPath: /data
        - name: log
          mountPath: /log
      volumes:
      - name: system
        persistentVolumeClaim:
          claimName: pvc-nfs-system
      - name: data
        persistentVolumeClaim:
          claimName: pvc-nfs-data
      - name: log
        persistentVolumeClaim:
          claimName: pvc-nfs-log
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort