start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
start cmd /c .\LoadScripts\GenerateLoad.bat
EXIT