start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S. -i .\LoadScripts\AGLoadGenerator1.sql
EXIT