apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
  labels:
    disk: data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.94.5
    path: "/srv/exports/volumes/sql-instance-2/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-log
  labels:
    disk: log
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.94.5
    path: "/srv/exports/volumes/sql-instance-2/log"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-system
  labels:
    disk: system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.94.5
    path: "/srv/exports/volumes/sql-instance-2/system"
