start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
start cmd /c sqlcmd -S.\SQL17 -i .\LoadScripts\AGLoadGenerator1.sql
EXIT