apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-instance
  labels:
    disk: system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.94.5
    path: "/export/volumes/sql1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-instance
spec:
  selector:
    matchLabels:
      disk: system
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi