USE [TestAG1];
GO

SET NOCOUNT ON;

WHILE (1=1)
BEGIN
	INSERT INTO T1 SELECT NEWID(), REPLICATE('a',7984)
	INSERT INTO T2 SELECT NEWID(), REPLICATE('a',7984)
	INSERT INTO T3 SELECT NEWID(), REPLICATE('a',7984)
	INSERT INTO T4 SELECT NEWID(), REPLICATE('a',7984)
	INSERT INTO T5 SELECT NEWID(), REPLICATE('a',7984)
END;
GO